version: '3.8'
services:
  svetlio-kafka-broker:
      image: 'bitnami/kafka:3.4.0'
      container_name: svetlio-kafka-broker
      platform: linux/x86_64
      ports:
        - '9094:9094'
      environment:
        - KAFKA_ENABLE_KRAFT=yes
        - KAFKA_CFG_PROCESS_ROLES=broker,controller
        - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - KAFKA_CFG_LISTENERS=EXTERNAL_SAME_HOST://:9094,INTERNAL://:9092,CONTROLLER://:9093
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
        - KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL_SAME_HOST://100.117.70.32:9094,INTERNAL://svetlio-kafka-broker:9092
        - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
        - KAFKA_CFG_LOG_RETENTION_MS=10000
        - KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS=5000
        - KAFKA_BROKER_ID=1
        - KAFKA_CFG_NODE_ID=1
        - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
        - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
        - ALLOW_PLAINTEXT_LISTENER=yes
      volumes:
        - kafka_data:/bitnami/kafka/data

volumes:
  kafka_data: